-- migrate:up

CREATE EXTENSION pgcrypto;

CREATE SCHEMA IF NOT EXISTS U1;

CREATE TABLE U1.USERS (
    ID UUID PRIMARY KEY NOT NULL DEFAULT public.gen_random_uuid(),
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(2) NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

-- migrate:down

DROP TABLE U1.USERS;
DROP SCHEMA U1;
